#ifndef __ENGINEER2_Parameter
#define __ENGINEER2_Parameter

/******************** 电机pid参数定义区域开始 ********************/

// 初始前伸速度环pid参数
#define PROTRACTION_LEFT_MOTOR_SPEED_INIT_PID_KP 4  // 40
#define PROTRACTION_LEFT_MOTOR_SPEED_INIT_PID_KI 0  // 0.01
#define PROTRACTION_LEFT_MOTOR_SPEED_INIT_PID_KD 0

#define PROTRACTION_RIGHT_MOTOR_SPEED_INIT_PID_KP 4  // 40
#define PROTRACTION_RIGHT_MOTOR_SPEED_INIT_PID_KI 0  // 0.01
#define PROTRACTION_RIGHT_MOTOR_SPEED_INIT_PID_KD 0

// 初始前伸角度环pid参数
#define PROTRACTION_LEFT_MOTOR_ANGLE_INIT_PID_KP 20  // 28
#define PROTRACTION_LEFT_MOTOR_ANGLE_INIT_PID_KI 0   // 0.03
#define PROTRACTION_LEFT_MOTOR_ANGLE_INIT_PID_KD 0

#define PROTRACTION_RIGHT_MOTOR_ANGLE_INIT_PID_KP 20  // 28
#define PROTRACTION_RIGHT_MOTOR_ANGLE_INIT_PID_KI 0   // 0.03
#define PROTRACTION_RIGHT_MOTOR_ANGLE_INIT_PID_KD 0

// 前伸速度环pid参数
#define PROTRACTION_LEFT_MOTOR_SPEED_PID_KP 4  // 40
#define PROTRACTION_LEFT_MOTOR_SPEED_PID_KI 0  // 0.01
#define PROTRACTION_LEFT_MOTOR_SPEED_PID_KD 0

#define PROTRACTION_RIGHT_MOTOR_SPEED_PID_KP 4  // 40
#define PROTRACTION_RIGHT_MOTOR_SPEED_PID_KI 0  // 0.01
#define PROTRACTION_RIGHT_MOTOR_SPEED_PID_KD 0

// 前伸角度环pid参数
#define PROTRACTION_LEFT_MOTOR_ANGLE_PID_KP 25  // 28
#define PROTRACTION_LEFT_MOTOR_ANGLE_PID_KI 0   // 0.03
#define PROTRACTION_LEFT_MOTOR_ANGLE_PID_KD 0

#define PROTRACTION_RIGHT_MOTOR_ANGLE_PID_KP 25  // 28
#define PROTRACTION_RIGHT_MOTOR_ANGLE_PID_KI 0   // 0.03
#define PROTRACTION_RIGHT_MOTOR_ANGLE_PID_KD 0

// 前伸电机最大输出
#define PROTRACTION_MOTOR_SPEED_MAX_OUT M2006_MAX_OUTPUT
#define PROTRACTION_MOTOR_SPEED_MAX_IOUT M2006_MAX_IOUTPUT
#define PROTRACTION_MOTOR_ANGLE_MAX_OUT 6000
#define PROTRACTION_MOTOR_ANGLE_MAX_IOUT 2000

//---------------------------------------机械臂无载参数-----------------------------------------
// 机械臂关节0双环pid参数
#define ARM_MOTOR0_ANGLE_PID_KP 20
#define ARM_MOTOR0_ANGLE_PID_KI 0.005
#define ARM_MOTOR0_ANGLE_PID_KD 0
#define ARM_MOTOR0_SPEED_PID_KP 8
#define ARM_MOTOR0_SPEED_PID_KI 0
#define ARM_MOTOR0_SPEED_PID_KD 0

// 机械臂关节1双环pid参数
#define ARM_MOTOR1_ANGLE_PID_KP 15
#define ARM_MOTOR1_ANGLE_PID_KI 0.05
#define ARM_MOTOR1_ANGLE_PID_KD 0
#define ARM_MOTOR1_SPEED_PID_KP 6
#define ARM_MOTOR1_SPEED_PID_KI 0
#define ARM_MOTOR1_SPEED_PID_KD 0

// 机械臂关节2双环pid参数
#define ARM_MOTOR2_ANGLE_PID_KP 15
#define ARM_MOTOR2_ANGLE_PID_KI 0.05
#define ARM_MOTOR2_ANGLE_PID_KD 0
#define ARM_MOTOR2_SPEED_PID_KP 6
#define ARM_MOTOR2_SPEED_PID_KI 0
#define ARM_MOTOR2_SPEED_PID_KD 0

// 机械臂关节3双环pid参数
#define ARM_MOTOR3_ANGLE_PID_KP 20
#define ARM_MOTOR3_ANGLE_PID_KI 0.04
#define ARM_MOTOR3_ANGLE_PID_KD 0
#define ARM_MOTOR3_SPEED_PID_KP 6
#define ARM_MOTOR3_SPEED_PID_KI 0
#define ARM_MOTOR3_SPEED_PID_KD 0

// 机械臂关节4双环pid参数
#define ARM_MOTOR4_ANGLE_PID_KP 20
#define ARM_MOTOR4_ANGLE_PID_KI 0.02
#define ARM_MOTOR4_ANGLE_PID_KD 0
#define ARM_MOTOR4_SPEED_PID_KP 6
#define ARM_MOTOR4_SPEED_PID_KI 0
#define ARM_MOTOR4_SPEED_PID_KD 0

// 机械臂关节5双环pid参数
#define ARM_MOTOR5_ANGLE_PID_KP 20
#define ARM_MOTOR5_ANGLE_PID_KI 0.02
#define ARM_MOTOR5_ANGLE_PID_KD 0
#define ARM_MOTOR5_SPEED_PID_KP 6
#define ARM_MOTOR5_SPEED_PID_KI 0
#define ARM_MOTOR5_SPEED_PID_KD 0
//---------------------------------------机械臂无载参数-----------------------------------------

//---------------------------------------机械臂带载参数-----------------------------------------
// 机械臂关节0双环pid参数
#define ARM_MOTOR0_ANGLE_STRONG_PID_KP 20
#define ARM_MOTOR0_ANGLE_STRONG_PID_KI 0
#define ARM_MOTOR0_ANGLE_STRONG_PID_KD 0
#define ARM_MOTOR0_SPEED_STRONG_PID_KP 10
#define ARM_MOTOR0_SPEED_STRONG_PID_KI 0
#define ARM_MOTOR0_SPEED_STRONG_PID_KD 0

// 机械臂关节1双环pid参数
#define ARM_MOTOR1_ANGLE_STRONG_PID_KP 20
#define ARM_MOTOR1_ANGLE_STRONG_PID_KI 0.05
#define ARM_MOTOR1_ANGLE_STRONG_PID_KD 0
#define ARM_MOTOR1_SPEED_STRONG_PID_KP 6
#define ARM_MOTOR1_SPEED_STRONG_PID_KI 0
#define ARM_MOTOR1_SPEED_STRONG_PID_KD 0

// 机械臂关节2双环pid参数
#define ARM_MOTOR2_ANGLE_STRONG_PID_KP 20
#define ARM_MOTOR2_ANGLE_STRONG_PID_KI 0.05
#define ARM_MOTOR2_ANGLE_STRONG_PID_KD 0
#define ARM_MOTOR2_SPEED_STRONG_PID_KP 6
#define ARM_MOTOR2_SPEED_STRONG_PID_KI 0
#define ARM_MOTOR2_SPEED_STRONG_PID_KD 0

// 机械臂关节3双环pid参数
#define ARM_MOTOR3_ANGLE_STRONG_PID_KP 20
#define ARM_MOTOR3_ANGLE_STRONG_PID_KI 0.04
#define ARM_MOTOR3_ANGLE_STRONG_PID_KD 0
#define ARM_MOTOR3_SPEED_STRONG_PID_KP 6
#define ARM_MOTOR3_SPEED_STRONG_PID_KI 0
#define ARM_MOTOR3_SPEED_STRONG_PID_KD 0

// 机械臂关节4双环pid参数
#define ARM_MOTOR4_ANGLE_STRONG_PID_KP 18
#define ARM_MOTOR4_ANGLE_STRONG_PID_KI 0.01
#define ARM_MOTOR4_ANGLE_STRONG_PID_KD 0
#define ARM_MOTOR4_SPEED_STRONG_PID_KP 6
#define ARM_MOTOR4_SPEED_STRONG_PID_KI 0
#define ARM_MOTOR4_SPEED_STRONG_PID_KD 0

// 机械臂关节5双环pid参数
#define ARM_MOTOR5_ANGLE_STRONG_PID_KP 20
#define ARM_MOTOR5_ANGLE_STRONG_PID_KI 0.01
#define ARM_MOTOR5_ANGLE_STRONG_PID_KD 0
#define ARM_MOTOR5_SPEED_STRONG_PID_KP 6
#define ARM_MOTOR5_SPEED_STRONG_PID_KI 0
#define ARM_MOTOR5_SPEED_STRONG_PID_KD 0
//---------------------------------------机械臂带载参数-----------------------------------------

//---------------------------------------机械臂初始化参数-----------------------------------------
// 机械臂关节0双环pid参数
#define ARM_MOTOR0_ANGLE_INIT_PID_KP 15
#define ARM_MOTOR0_ANGLE_INIT_PID_KI 0
#define ARM_MOTOR0_ANGLE_INIT_PID_KD 0
#define ARM_MOTOR0_SPEED_INIT_PID_KP 6
#define ARM_MOTOR0_SPEED_INIT_PID_KI 0
#define ARM_MOTOR0_SPEED_INIT_PID_KD 0

// 机械臂关节1双环pid参数
#define ARM_MOTOR1_ANGLE_INIT_PID_KP 30
#define ARM_MOTOR1_ANGLE_INIT_PID_KI 0
#define ARM_MOTOR1_ANGLE_INIT_PID_KD 0
#define ARM_MOTOR1_SPEED_INIT_PID_KP 10
#define ARM_MOTOR1_SPEED_INIT_PID_KI 0
#define ARM_MOTOR1_SPEED_INIT_PID_KD 0

// 机械臂关节2双环pid参数
#define ARM_MOTOR2_ANGLE_INIT_PID_KP 35
#define ARM_MOTOR2_ANGLE_INIT_PID_KI 0
#define ARM_MOTOR2_ANGLE_INIT_PID_KD 0
#define ARM_MOTOR2_SPEED_INIT_PID_KP 8
#define ARM_MOTOR2_SPEED_INIT_PID_KI 0
#define ARM_MOTOR2_SPEED_INIT_PID_KD 0

// 机械臂关节3双环pid参数
#define ARM_MOTOR3_ANGLE_INIT_PID_KP 20
#define ARM_MOTOR3_ANGLE_INIT_PID_KI 0
#define ARM_MOTOR3_ANGLE_INIT_PID_KD 0
#define ARM_MOTOR3_SPEED_INIT_PID_KP 8
#define ARM_MOTOR3_SPEED_INIT_PID_KI 0
#define ARM_MOTOR3_SPEED_INIT_PID_KD 0

// 机械臂关节4双环pid参数
#define ARM_MOTOR4_ANGLE_INIT_PID_KP 18
#define ARM_MOTOR4_ANGLE_INIT_PID_KI 0
#define ARM_MOTOR4_ANGLE_INIT_PID_KD 0
#define ARM_MOTOR4_SPEED_INIT_PID_KP 6
#define ARM_MOTOR4_SPEED_INIT_PID_KI 0
#define ARM_MOTOR4_SPEED_INIT_PID_KD 0

// 机械臂关节5双环pid参数
#define ARM_MOTOR5_ANGLE_INIT_PID_KP 10
#define ARM_MOTOR5_ANGLE_INIT_PID_KI 0
#define ARM_MOTOR5_ANGLE_INIT_PID_KD 0
#define ARM_MOTOR5_SPEED_INIT_PID_KP 6
#define ARM_MOTOR5_SPEED_INIT_PID_KI 0
#define ARM_MOTOR5_SPEED_INIT_PID_KD 0
//---------------------------------------机械臂初始化参数-----------------------------------------

#define ARM_MOTOR0_SPEED_MAX_OUT M2006_MAX_OUTPUT
#define ARM_MOTOR0_SPEED_MAX_IOUT M2006_MAX_IOUTPUT
#define ARM_MOTOR1_SPEED_MAX_OUT M3508_MAX_OUTPUT
#define ARM_MOTOR1_SPEED_MAX_IOUT M3508_MAX_IOUTPUT
#define ARM_MOTOR2_SPEED_MAX_OUT M3508_MAX_OUTPUT
#define ARM_MOTOR2_SPEED_MAX_IOUT M3508_MAX_IOUTPUT
#define ARM_MOTOR3_SPEED_MAX_OUT M3508_MAX_OUTPUT
#define ARM_MOTOR3_SPEED_MAX_IOUT M3508_MAX_IOUTPUT
#define ARM_MOTOR4_SPEED_MAX_OUT M2006_MAX_OUTPUT
#define ARM_MOTOR4_SPEED_MAX_IOUT M2006_MAX_IOUTPUT
#define ARM_MOTOR5_SPEED_MAX_OUT M2006_MAX_OUTPUT
#define ARM_MOTOR5_SPEED_MAX_IOUT M2006_MAX_IOUTPUT

#define ARM_MOTOR0_ANGLE_MAX_OUT 6000.0
#define ARM_MOTOR0_ANGLE_MAX_IOUT 800.0
#define ARM_MOTOR1_ANGLE_MAX_OUT 2000.0
#define ARM_MOTOR1_ANGLE_MAX_IOUT 800.0
#define ARM_MOTOR2_ANGLE_MAX_OUT 1000.0
#define ARM_MOTOR2_ANGLE_MAX_IOUT 50.0
#define ARM_MOTOR3_ANGLE_MAX_OUT 2500.0
#define ARM_MOTOR3_ANGLE_MAX_IOUT 400.0
#define ARM_MOTOR4_ANGLE_MAX_OUT 3000.0
#define ARM_MOTOR4_ANGLE_MAX_IOUT 800.0
#define ARM_MOTOR5_ANGLE_MAX_OUT 3000.0
#define ARM_MOTOR5_ANGLE_MAX_IOUT 800.0

#define ARM_MOTOR0_ANGLE_MAX 36000
#define ARM_MOTOR0_ANGLE_MIN -36000
#define ARM_MOTOR1_ANGLE_MAX 200
#define ARM_MOTOR1_ANGLE_MIN 20
#define ARM_MOTOR2_ANGLE_MAX 50
#define ARM_MOTOR2_ANGLE_MIN -60
#define ARM_MOTOR3_ANGLE_MAX 36000
#define ARM_MOTOR3_ANGLE_MIN -36000
#define ARM_MOTOR4_ANGLE_MAX 36000
#define ARM_MOTOR4_ANGLE_MIN -36000
#define ARM_MOTOR5_ANGLE_MAX 36000
#define ARM_MOTOR5_ANGLE_MIN -36000

//---------------------------------------银矿初始化参数-----------------------------------------
// 机械臂关节0双环pid参数
#define SILVER_MOTOR0_ANGLE_INIT_PID_KP 10
#define SILVER_MOTOR0_ANGLE_INIT_PID_KI 0
#define SILVER_MOTOR0_ANGLE_INIT_PID_KD 0
#define SILVER_MOTOR0_SPEED_INIT_PID_KP 5
#define SILVER_MOTOR0_SPEED_INIT_PID_KI 0
#define SILVER_MOTOR0_SPEED_INIT_PID_KD 0

// 机械臂关节1双环pid参数
#define SILVER_MOTOR1_ANGLE_INIT_PID_KP 15
#define SILVER_MOTOR1_ANGLE_INIT_PID_KI 0
#define SILVER_MOTOR1_ANGLE_INIT_PID_KD 0
#define SILVER_MOTOR1_SPEED_INIT_PID_KP 6
#define SILVER_MOTOR1_SPEED_INIT_PID_KI 0
#define SILVER_MOTOR1_SPEED_INIT_PID_KD 0

// 机械臂关节2双环pid参数
#define SILVER_MOTOR2_ANGLE_INIT_PID_KP 15
#define SILVER_MOTOR2_ANGLE_INIT_PID_KI 0
#define SILVER_MOTOR2_ANGLE_INIT_PID_KD 0
#define SILVER_MOTOR2_SPEED_INIT_PID_KP 6
#define SILVER_MOTOR2_SPEED_INIT_PID_KI 0
#define SILVER_MOTOR2_SPEED_INIT_PID_KD 0

// 机械臂关节3双环pid参数
#define SILVER_MOTOR3_ANGLE_INIT_PID_KP 15
#define SILVER_MOTOR3_ANGLE_INIT_PID_KI 0
#define SILVER_MOTOR3_ANGLE_INIT_PID_KD 0
#define SILVER_MOTOR3_SPEED_INIT_PID_KP 6
#define SILVER_MOTOR3_SPEED_INIT_PID_KI 0
#define SILVER_MOTOR3_SPEED_INIT_PID_KD 0

//---------------------------------------银矿初始化参数-----------------------------------------

//---------------------------------------银矿普通参数-----------------------------------------
// 机械臂关节0双环pid参数
#define SILVER_MOTOR0_ANGLE_PID_KP 10
#define SILVER_MOTOR0_ANGLE_PID_KI 0
#define SILVER_MOTOR0_ANGLE_PID_KD 0
#define SILVER_MOTOR0_SPEED_PID_KP 5
#define SILVER_MOTOR0_SPEED_PID_KI 0
#define SILVER_MOTOR0_SPEED_PID_KD 0

// 机械臂关节1双环pid参数
#define SILVER_MOTOR1_ANGLE_PID_KP 15
#define SILVER_MOTOR1_ANGLE_PID_KI 0
#define SILVER_MOTOR1_ANGLE_PID_KD 0
#define SILVER_MOTOR1_SPEED_PID_KP 6
#define SILVER_MOTOR1_SPEED_PID_KI 0
#define SILVER_MOTOR1_SPEED_PID_KD 0

// 机械臂关节2双环pid参数
#define SILVER_MOTOR2_ANGLE_PID_KP 15
#define SILVER_MOTOR2_ANGLE_PID_KI 0
#define SILVER_MOTOR2_ANGLE_PID_KD 0
#define SILVER_MOTOR2_SPEED_PID_KP 6
#define SILVER_MOTOR2_SPEED_PID_KI 0
#define SILVER_MOTOR2_SPEED_PID_KD 0

// 机械臂关节3双环pid参数
#define SILVER_MOTOR3_ANGLE_PID_KP 15
#define SILVER_MOTOR3_ANGLE_PID_KI 0
#define SILVER_MOTOR3_ANGLE_PID_KD 0
#define SILVER_MOTOR3_SPEED_PID_KP 6
#define SILVER_MOTOR3_SPEED_PID_KI 0
#define SILVER_MOTOR3_SPEED_PID_KD 0

//---------------------------------------银矿普通参数-----------------------------------------

//---------------------------------------金矿初始化参数-----------------------------------------
// 机械臂关节0双环pid参数
#define GOLD_MOTOR0_ANGLE_INIT_PID_KP 15
#define GOLD_MOTOR0_ANGLE_INIT_PID_KI 0
#define GOLD_MOTOR0_ANGLE_INIT_PID_KD 0
#define GOLD_MOTOR0_SPEED_INIT_PID_KP 6
#define GOLD_MOTOR0_SPEED_INIT_PID_KI 0
#define GOLD_MOTOR0_SPEED_INIT_PID_KD 0

// 机械臂关节1双环pid参数
#define GOLD_MOTOR1_ANGLE_INIT_PID_KP 15
#define GOLD_MOTOR1_ANGLE_INIT_PID_KI 0
#define GOLD_MOTOR1_ANGLE_INIT_PID_KD 0
#define GOLD_MOTOR1_SPEED_INIT_PID_KP 6
#define GOLD_MOTOR1_SPEED_INIT_PID_KI 0
#define GOLD_MOTOR1_SPEED_INIT_PID_KD 0

// 机械臂关节2双环pid参数
#define GOLD_MOTOR2_ANGLE_INIT_PID_KP 15
#define GOLD_MOTOR2_ANGLE_INIT_PID_KI 0
#define GOLD_MOTOR2_ANGLE_INIT_PID_KD 0
#define GOLD_MOTOR2_SPEED_INIT_PID_KP 6
#define GOLD_MOTOR2_SPEED_INIT_PID_KI 0
#define GOLD_MOTOR2_SPEED_INIT_PID_KD 0

// 机械臂关节3双环pid参数
#define GOLD_MOTOR3_ANGLE_INIT_PID_KP 15
#define GOLD_MOTOR3_ANGLE_INIT_PID_KI 0
#define GOLD_MOTOR3_ANGLE_INIT_PID_KD 0
#define GOLD_MOTOR3_SPEED_INIT_PID_KP 6
#define GOLD_MOTOR3_SPEED_INIT_PID_KI 0
#define GOLD_MOTOR3_SPEED_INIT_PID_KD 0

//---------------------------------------金矿初始化参数-----------------------------------------

//---------------------------------------金矿普通参数-----------------------------------------
// 机械臂关节0双环pid参数
#define GOLD_MOTOR0_ANGLE_PID_KP 16
#define GOLD_MOTOR0_ANGLE_PID_KI 0
#define GOLD_MOTOR0_ANGLE_PID_KD 0
#define GOLD_MOTOR0_SPEED_PID_KP 6
#define GOLD_MOTOR0_SPEED_PID_KI 0
#define GOLD_MOTOR0_SPEED_PID_KD 0

// 机械臂关节1双环pid参数
#define GOLD_MOTOR1_ANGLE_PID_KP 20
#define GOLD_MOTOR1_ANGLE_PID_KI 0
#define GOLD_MOTOR1_ANGLE_PID_KD 0
#define GOLD_MOTOR1_SPEED_PID_KP 5
#define GOLD_MOTOR1_SPEED_PID_KI 0
#define GOLD_MOTOR1_SPEED_PID_KD 0

// 机械臂关节2双环pid参数
#define GOLD_MOTOR2_ANGLE_PID_KP 16
#define GOLD_MOTOR2_ANGLE_PID_KI 0
#define GOLD_MOTOR2_ANGLE_PID_KD 0
#define GOLD_MOTOR2_SPEED_PID_KP 6
#define GOLD_MOTOR2_SPEED_PID_KI 0
#define GOLD_MOTOR2_SPEED_PID_KD 0

// 机械臂关节3双环pid参数
#define GOLD_MOTOR3_ANGLE_PID_KP 20
#define GOLD_MOTOR3_ANGLE_PID_KI 0
#define GOLD_MOTOR3_ANGLE_PID_KD 0
#define GOLD_MOTOR3_SPEED_PID_KP 5
#define GOLD_MOTOR3_SPEED_PID_KI 0
#define GOLD_MOTOR3_SPEED_PID_KD 0

//---------------------------------------金矿普通参数-----------------------------------------

// 云台YAW速度环参数
#define VIEW_MOTO_YAW_SPEED_KP 0.18f
#define VIEW_MOTO_YAW_SPEED_KI 0.0f
#define VIEW_MOTO_YAW_SPEED_KD 0.005f

// 云台YAW角度环参数
#define VIEW_MOTO_YAW_ANGLE_KP 50.0f  // 1.2f
#define VIEW_MOTO_YAW_ANGLE_KI 0.0f   // 0.12f
#define VIEW_MOTO_YAW_ANGLE_KD 0      // 0

// 最大YAW速度输出
#define MAX_YAW_SPEED_OUT 1000.0f  // 10.0f
#define MAX_YAW_SPEED_IOUT 0.0f

// 最大YAW角度输出
#define MAX_YAW_ANGLE_OUT 2500.0f
#define MAX_YAW_ANGLE_IOUT 100.0f  // 150.0f

/******************** 电机pid参数定义区域结束 ********************/


/******************** 电机pid参数定义区域结束 ********************/

/******************** 电机pid参数定义区域结束 ********************/

// 真空泵状态
#define PUMP0_STATE 0x01
#define PUMP1_STATE 0x02
#define PUMP2_STATE 0x04
#define PUMP3_STATE 0x08

#define PUMP0_CHANNEL 0x10
#define PUMP1_CHANNEL 0x20
#define PUMP2_CHANNEL 0x40
#define PUMP3_CHANNEL 0x80

// 定义长按时间
#define LONG_PRESSED_TIME 1000

// 定义吸盘形成真空所需时间
#define VACUUM_TIME 1000

#endif
